name = "ankimcp"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "anki-cards"
database_id = "537b453d-c00b-45b8-9a6d-f34ca13a0a1b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "anki-decks"
